[package]

name = "gta"
version = "0.0.1"
authors = ["Rottis <rottis@fea.st>"]

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
[dependencies.piston]
git = "https://github.com/PistonDevelopers/piston.git"
[dependencies.glfw_game_window]
git = "https://github.com/PistonDevelopers/glfw_game_window.git"

